#!/bin/bash

CLIENT_IP=$1
EXTERNAL_IP=$2
RULE=$3

tcp_ports="27030:27039"
udp_ports="1200,27000:27015"

echo "${RULE} locl:${CLIENT_IP} inet udp ${udp_ports}"
echo "${RULE} locl:${CLIENT_IP} inet tcp ${tcp_ports}"
