#!/bin/bash

CLIENT_IP=$1

echo "POP3(ACCEPT)    locl:${CLIENT_IP}    \$FW"
echo "POP3S(ACCEPT)   locl:${CLIENT_IP}    \$FW"
echo "SMTP(ACCEPT)    locl:${CLIENT_IP}    \$FW"
echo "SMTPS(ACCEPT)   locl:${CLIENT_IP}    \$FW"
echo "IMAP(ACCEPT)    locl:${CLIENT_IP}    \$FW"
echo "IMAPS(ACCEPT)   locl:${CLIENT_IP}    \$FW"
