#!/bin/bash

CLIENT_IP=$1
EXTERNAL_IP=$2
RULE=$3

echo "POP3(${RULE})    locl:${CLIENT_IP}    \$FW"
echo "POP3S(${RULE})   locl:${CLIENT_IP}    \$FW"
echo "SMTP(${RULE})    locl:${CLIENT_IP}    \$FW"
echo "SMTPS(${RULE})   locl:${CLIENT_IP}    \$FW"
echo "IMAP(${RULE})    locl:${CLIENT_IP}    \$FW"
echo "IMAPS(${RULE})   locl:${CLIENT_IP}    \$FW"
