#!/bin/bash

CLIENT_IP=$1
EXTERNAL_IP=$2
RULE=$3

address="http://dpmaster.deathmask.net/?game=nexuiz"
ports="26000"
#for p in $(wget "http://dpmaster.deathmask.net/?game=nexuiz" -q -O - | egrep -o ":[0-9]+" | sort -u | sed -e 's/://')
#do
#  ports="${ports},${p}"
#done

echo "${RULE} locl:${CLIENT_IP} inet udp ${ports}"
