#!/bin/bash

CLIENT_IP=$1



ports="27960"
#for p in $(cat /etc/shorewall/rules.d/services/ws_serverscache.txt | grep ":" | sed -e "s/.*:\\([0-9]*\\) .*/\\1/" | sort -u)
#do
#  ports="${ports},${p}"
#done

echo "ACCEPT locl:${CLIENT_IP} inet udp ${ports}"
