#!/usr/bin/perl

do '/etc/configuration-generator/hosts.conf'; our ($network);
do '/etc/configuration-generator/squid.conf'; our ($ruleconfig);

my ($client_ip, $external_ip)=@ARGV[0..1];

for my $t ('tcp', 'udp')
{
    printf ("REDIRECT locl:%s %d %s %s - !%s\n",
	    $client_ip,
	    $ruleconfig->{'squid-port'},
	    $t,
	    join(',', @{$ruleconfig->{'redirect-ports'}}),
	    join(',', ($external_ip, $network->{'router'})));
    printf ("ACCEPT locl:%s inet %s https\n", $client_ip, $t)
}

printf ("HTTP(ACCEPT) locl:%s \$FW\n", $client_ip);
printf ("HTTPS(ACCEPT) locl:%s \$FW\n", $client_ip);

# flash player
printf ("ACCEPT locl:%s inet udp 843\n", $client_ip);
printf ("ACCEPT locl:%s inet tcp 843\n", $client_ip);
