#!/bin/bash

CLIENT_IP=$1

echo "FTP(ACCEPT) locl:${CLIENT_IP} inet"

#FROX_IP=192.168.1.1
#FROX_PORT=2128
#FROX_PORTS="21"
#CLIENT_IP=$1

#for t in tcp udp
#do
#    echo "REDIRECT locl:${CLIENT_IP} ${FROX_PORT} ${t} ${FROX_PORTS} - !192.168.1.1,88.215.138.24,192.168.0.2,192.168.0.1"
#done

